FROM python:3.9

WORKDIR /app


COPY requirements.txt requirements.txt
COPY api.py api.py
COPY image_processor.py image_processor.py
COPY index.pickle index.pickle
COPY final_model/weights.pt final_model/weights.py
COPY final_embeddings.json final_embeddings.json

RUN apt-get update
RUN apt-get install \
    'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
RUN pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python3", "api.py"]
